### ISSUE TITLE
[FR] Add transition value to dimmer script

### ISSUE THREAD

**Issue by cyberporkexception** [SirGoodenough/HA_Blueprints#24]
**Which Blueprint is This Concern About / Related To?**
https://github.com/SirGoodenough/HA_Blueprints/blob/master/Scripts/dimmer_control_4_magic_cube.yaml

**Is your feature request related to a problem? Please describe.**
Transition happens really jerkily while dimming with a rotation of the cube.

**Describe the solution you'd like**
A customizable input field where you can specify how long the transition should last.

**Describe alternatives you've considered**
None

**Additional context**
I added a static transition value in your blueprint, works well.

**Comment by SirGoodenough** [comment]
I hesitate a bit because some lights do not accept transition and I do not want to cause an issue with those. The focus there was dimming only.
Here are some examples and reasons that you can add to this BP on your own.
Perhaps if I hear more requests for this, I will consider it.  I will keep this issue open for a while to see.

https://community.home-assistant.io/t/dimming-over-time-with-transition/456054

**Comment by cyberporkexception** [comment]
Usually lights which not support/accept transition just not respond to that

**Comment by SirGoodenough** [comment]
The problem is lights that do use it.  It can't be blank, so do I default it to 0, possibly messing someone settings up?
OR
I'm visioning a complicated only show transition if the transition value is provided by user, or only show transition if transition is a skill the light has and find that out thru decoding the light device features code.

**Comment by SirGoodenough** [comment]
@cyberporkexception 
I gave it a shot, try it out.  I don't know if I have any transition lights in the house...

Adding transition as data when calling the script has priority.  If that is not there, the !input can set the transition. If you call the script with data and have a different number loaded as an input, the data call value will over-ride the input.  If neither is set to a number, the transition value should not show in the trace at all.
Please check these all out if you can.

I set max transition to a half hour in half second increments. Might be overkill, but it is available so why not.  Don't have to test that, just that sending the data to and thru the BP all works.

Test Version:
https://github.com/SirGoodenough/HA_Blueprints/blob/transition/Scripts/dimmer_control_4_magic_cube.yaml

**Comment by SirGoodenough** [comment]
With no objections...
#28
